version: '3'

services:
  #  docker run -d --name axonserver -p 8024:8024 -p 8124:8124 axoniq/axonserver
  axon-server:
    image: axoniq/axonserver:4.5.14
    ports:
      - 8024:8024
      - 8124:8124
    volumes:
      - axon-data:/data
      - axon-eventdata:/eventdata
      - C:\Users\Admin\IdeaProjects\Study\SergeyKargopolov\CQRS_SAGA_Axon_Microservices\art-kargopolov-cqrs-saga-axon-microservices\docker-compose\product-service\config:/config

  product-service:
    image: artarkatesoft/cqrs-product-service
    ports:
    - 8090:8080
    environment:
      "eureka.client.enabled": "false"
      "spring.datasource.url": 'jdbc:h2:mem:testdb'
      "spring.datasource.username": 'sa'
      "spring.datasource.password": ''
      "axon.axonserver.servers": "axon-server:8124"

volumes:
  axon-data:
  axon-eventdata:
